/**
 * Versify API
 * Versify API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VersifyClient);
  }
}(this, function(expect, VersifyClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VersifyClient.ContactsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactsApi', function() {
    describe('createContactV2ContactsPost', function() {
      it('should call createContactV2ContactsPost successfully', function(done) {
        //uncomment below and update the code to test createContactV2ContactsPost
        //instance.createContactV2ContactsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createContactV2ContactsPost_0', function() {
      it('should call createContactV2ContactsPost_0 successfully', function(done) {
        //uncomment below and update the code to test createContactV2ContactsPost_0
        //instance.createContactV2ContactsPost_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteContactV2ContactsContactIdDelete', function() {
      it('should call deleteContactV2ContactsContactIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteContactV2ContactsContactIdDelete
        //instance.deleteContactV2ContactsContactIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteContactV2ContactsContactIdDelete_0', function() {
      it('should call deleteContactV2ContactsContactIdDelete_0 successfully', function(done) {
        //uncomment below and update the code to test deleteContactV2ContactsContactIdDelete_0
        //instance.deleteContactV2ContactsContactIdDelete_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactV2ContactsContactIdGet', function() {
      it('should call getContactV2ContactsContactIdGet successfully', function(done) {
        //uncomment below and update the code to test getContactV2ContactsContactIdGet
        //instance.getContactV2ContactsContactIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactV2ContactsContactIdGet_0', function() {
      it('should call getContactV2ContactsContactIdGet_0 successfully', function(done) {
        //uncomment below and update the code to test getContactV2ContactsContactIdGet_0
        //instance.getContactV2ContactsContactIdGet_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listContactsV2ContactsGet', function() {
      it('should call listContactsV2ContactsGet successfully', function(done) {
        //uncomment below and update the code to test listContactsV2ContactsGet
        //instance.listContactsV2ContactsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listContactsV2ContactsGet_0', function() {
      it('should call listContactsV2ContactsGet_0 successfully', function(done) {
        //uncomment below and update the code to test listContactsV2ContactsGet_0
        //instance.listContactsV2ContactsGet_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchContactsV2ContactsSearchPost', function() {
      it('should call searchContactsV2ContactsSearchPost successfully', function(done) {
        //uncomment below and update the code to test searchContactsV2ContactsSearchPost
        //instance.searchContactsV2ContactsSearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchContactsV2ContactsSearchPost_0', function() {
      it('should call searchContactsV2ContactsSearchPost_0 successfully', function(done) {
        //uncomment below and update the code to test searchContactsV2ContactsSearchPost_0
        //instance.searchContactsV2ContactsSearchPost_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateContactV2ContactsContactIdPut', function() {
      it('should call updateContactV2ContactsContactIdPut successfully', function(done) {
        //uncomment below and update the code to test updateContactV2ContactsContactIdPut
        //instance.updateContactV2ContactsContactIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateContactV2ContactsContactIdPut_0', function() {
      it('should call updateContactV2ContactsContactIdPut_0 successfully', function(done) {
        //uncomment below and update the code to test updateContactV2ContactsContactIdPut_0
        //instance.updateContactV2ContactsContactIdPut_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
