/**
 * Versify API
 * Versify API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VersifylabsVersifyClient);
  }
}(this, function(expect, VersifylabsVersifyClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VersifylabsVersifyClient.Asset9();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Asset9', function() {
    it('should create an instance of Asset9', function() {
      // uncomment below and update the code to test Asset9
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be.a(VersifylabsVersifyClient.Asset9);
    });

    it('should have the property asset (base name: "asset")', function() {
      // uncomment below and update the code to test the property asset
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property assetQuantity (base name: "asset_quantity")', function() {
      // uncomment below and update the code to test the property assetQuantity
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property image (base name: "image")', function() {
      // uncomment below and update the code to test the property image
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

    it('should have the property rewardType (base name: "reward_type")', function() {
      // uncomment below and update the code to test the property rewardType
      //var instance = new VersifylabsVersifyClient.Asset9();
      //expect(instance).to.be();
    });

  });

}));
