/**
 * Versify API
 * Versify API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VersifyApi);
  }
}(this, function(expect, VersifyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VersifyApi.Billing();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Billing', function() {
    it('should create an instance of Billing', function() {
      // uncomment below and update the code to test Billing
      //var instance = new VersifyApi.Billing();
      //expect(instance).to.be.a(VersifyApi.Billing);
    });

    it('should have the property stripeCustomerId (base name: "stripe_customer_id")', function() {
      // uncomment below and update the code to test the property stripeCustomerId
      //var instance = new VersifyApi.Billing();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionPlan (base name: "subscription_plan")', function() {
      // uncomment below and update the code to test the property subscriptionPlan
      //var instance = new VersifyApi.Billing();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionStatus (base name: "subscription_status")', function() {
      // uncomment below and update the code to test the property subscriptionStatus
      //var instance = new VersifyApi.Billing();
      //expect(instance).to.be();
    });

  });

}));
