/**
 * Versify API
 * Versify API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Account from './model/Account';
import AccountStatus from './model/AccountStatus';
import ApiDeleteResponse from './model/ApiDeleteResponse';
import ApiListResponse from './model/ApiListResponse';
import ApiSearchResponse from './model/ApiSearchResponse';
import App from './model/App';
import Asset from './model/Asset';
import Asset1 from './model/Asset1';
import AssetCreate from './model/AssetCreate';
import AssetStatus from './model/AssetStatus';
import AssetUpdate from './model/AssetUpdate';
import Billing from './model/Billing';
import BillingSettings from './model/BillingSettings';
import BlockchainType from './model/BlockchainType';
import Brand from './model/Brand';
import BrandingSettings from './model/BrandingSettings';
import Contact from './model/Contact';
import HTTPValidationError from './model/HTTPValidationError';
import LocationInner from './model/LocationInner';
import Operator from './model/Operator';
import Query from './model/Query';
import Query1 from './model/Query1';
import QueryValue from './model/QueryValue';
import SearchContacts from './model/SearchContacts';
import SearchQuery from './model/SearchQuery';
import SubscriptionPlan from './model/SubscriptionPlan';
import SubscriptionStatus from './model/SubscriptionStatus';
import TeamMember from './model/TeamMember';
import TeamMemberRole from './model/TeamMemberRole';
import ValidationError from './model/ValidationError';
import WalletPosition from './model/WalletPosition';
import AssetsApi from './api/AssetsApi';


/**
* Versify API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var VersifylabsVersifyClient = require('index'); // See note below*.
* var xxxSvc = new VersifylabsVersifyClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new VersifylabsVersifyClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new VersifylabsVersifyClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new VersifylabsVersifyClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account,

    /**
     * The AccountStatus model constructor.
     * @property {module:model/AccountStatus}
     */
    AccountStatus,

    /**
     * The ApiDeleteResponse model constructor.
     * @property {module:model/ApiDeleteResponse}
     */
    ApiDeleteResponse,

    /**
     * The ApiListResponse model constructor.
     * @property {module:model/ApiListResponse}
     */
    ApiListResponse,

    /**
     * The ApiSearchResponse model constructor.
     * @property {module:model/ApiSearchResponse}
     */
    ApiSearchResponse,

    /**
     * The App model constructor.
     * @property {module:model/App}
     */
    App,

    /**
     * The Asset model constructor.
     * @property {module:model/Asset}
     */
    Asset,

    /**
     * The Asset1 model constructor.
     * @property {module:model/Asset1}
     */
    Asset1,

    /**
     * The AssetCreate model constructor.
     * @property {module:model/AssetCreate}
     */
    AssetCreate,

    /**
     * The AssetStatus model constructor.
     * @property {module:model/AssetStatus}
     */
    AssetStatus,

    /**
     * The AssetUpdate model constructor.
     * @property {module:model/AssetUpdate}
     */
    AssetUpdate,

    /**
     * The Billing model constructor.
     * @property {module:model/Billing}
     */
    Billing,

    /**
     * The BillingSettings model constructor.
     * @property {module:model/BillingSettings}
     */
    BillingSettings,

    /**
     * The BlockchainType model constructor.
     * @property {module:model/BlockchainType}
     */
    BlockchainType,

    /**
     * The Brand model constructor.
     * @property {module:model/Brand}
     */
    Brand,

    /**
     * The BrandingSettings model constructor.
     * @property {module:model/BrandingSettings}
     */
    BrandingSettings,

    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The LocationInner model constructor.
     * @property {module:model/LocationInner}
     */
    LocationInner,

    /**
     * The Operator model constructor.
     * @property {module:model/Operator}
     */
    Operator,

    /**
     * The Query model constructor.
     * @property {module:model/Query}
     */
    Query,

    /**
     * The Query1 model constructor.
     * @property {module:model/Query1}
     */
    Query1,

    /**
     * The QueryValue model constructor.
     * @property {module:model/QueryValue}
     */
    QueryValue,

    /**
     * The SearchContacts model constructor.
     * @property {module:model/SearchContacts}
     */
    SearchContacts,

    /**
     * The SearchQuery model constructor.
     * @property {module:model/SearchQuery}
     */
    SearchQuery,

    /**
     * The SubscriptionPlan model constructor.
     * @property {module:model/SubscriptionPlan}
     */
    SubscriptionPlan,

    /**
     * The SubscriptionStatus model constructor.
     * @property {module:model/SubscriptionStatus}
     */
    SubscriptionStatus,

    /**
     * The TeamMember model constructor.
     * @property {module:model/TeamMember}
     */
    TeamMember,

    /**
     * The TeamMemberRole model constructor.
     * @property {module:model/TeamMemberRole}
     */
    TeamMemberRole,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The WalletPosition model constructor.
     * @property {module:model/WalletPosition}
     */
    WalletPosition,

    /**
    * The AssetsApi service constructor.
    * @property {module:api/AssetsApi}
    */
    AssetsApi
};
