/**
 * Versify API
 * Versify API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VersifylabsVersifyClient);
  }
}(this, function(expect, VersifylabsVersifyClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VersifylabsVersifyClient.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('accessTokenV2OauthAccessTokenPost', function() {
      it('should call accessTokenV2OauthAccessTokenPost successfully', function(done) {
        //uncomment below and update the code to test accessTokenV2OauthAccessTokenPost
        //instance.accessTokenV2OauthAccessTokenPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('accessTokenV2OauthAccessTokenPost_0', function() {
      it('should call accessTokenV2OauthAccessTokenPost_0 successfully', function(done) {
        //uncomment below and update the code to test accessTokenV2OauthAccessTokenPost_0
        //instance.accessTokenV2OauthAccessTokenPost_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authorizeV2OauthAuthorizeGet', function() {
      it('should call authorizeV2OauthAuthorizeGet successfully', function(done) {
        //uncomment below and update the code to test authorizeV2OauthAuthorizeGet
        //instance.authorizeV2OauthAuthorizeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authorizeV2OauthAuthorizeGet_0', function() {
      it('should call authorizeV2OauthAuthorizeGet_0 successfully', function(done) {
        //uncomment below and update the code to test authorizeV2OauthAuthorizeGet_0
        //instance.authorizeV2OauthAuthorizeGet_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
