/**
 * Versify API
 * Versify API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VersifyClient);
  }
}(this, function(expect, VersifyClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VersifyClient.MintsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MintsApi', function() {
    describe('createMintV2MintsPost', function() {
      it('should call createMintV2MintsPost successfully', function(done) {
        //uncomment below and update the code to test createMintV2MintsPost
        //instance.createMintV2MintsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createMintV2MintsPost_0', function() {
      it('should call createMintV2MintsPost_0 successfully', function(done) {
        //uncomment below and update the code to test createMintV2MintsPost_0
        //instance.createMintV2MintsPost_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMintV2MintsMintIdDelete', function() {
      it('should call deleteMintV2MintsMintIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteMintV2MintsMintIdDelete
        //instance.deleteMintV2MintsMintIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMintV2MintsMintIdDelete_0', function() {
      it('should call deleteMintV2MintsMintIdDelete_0 successfully', function(done) {
        //uncomment below and update the code to test deleteMintV2MintsMintIdDelete_0
        //instance.deleteMintV2MintsMintIdDelete_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMintV2MintsMintIdGet', function() {
      it('should call getMintV2MintsMintIdGet successfully', function(done) {
        //uncomment below and update the code to test getMintV2MintsMintIdGet
        //instance.getMintV2MintsMintIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMintV2MintsMintIdGet_0', function() {
      it('should call getMintV2MintsMintIdGet_0 successfully', function(done) {
        //uncomment below and update the code to test getMintV2MintsMintIdGet_0
        //instance.getMintV2MintsMintIdGet_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMintsV2MintsGet', function() {
      it('should call listMintsV2MintsGet successfully', function(done) {
        //uncomment below and update the code to test listMintsV2MintsGet
        //instance.listMintsV2MintsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMintsV2MintsGet_0', function() {
      it('should call listMintsV2MintsGet_0 successfully', function(done) {
        //uncomment below and update the code to test listMintsV2MintsGet_0
        //instance.listMintsV2MintsGet_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchMintsV2MintsSearchPost', function() {
      it('should call searchMintsV2MintsSearchPost successfully', function(done) {
        //uncomment below and update the code to test searchMintsV2MintsSearchPost
        //instance.searchMintsV2MintsSearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchMintsV2MintsSearchPost_0', function() {
      it('should call searchMintsV2MintsSearchPost_0 successfully', function(done) {
        //uncomment below and update the code to test searchMintsV2MintsSearchPost_0
        //instance.searchMintsV2MintsSearchPost_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMintV2MintsMintIdPut', function() {
      it('should call updateMintV2MintsMintIdPut successfully', function(done) {
        //uncomment below and update the code to test updateMintV2MintsMintIdPut
        //instance.updateMintV2MintsMintIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMintV2MintsMintIdPut_0', function() {
      it('should call updateMintV2MintsMintIdPut_0 successfully', function(done) {
        //uncomment below and update the code to test updateMintV2MintsMintIdPut_0
        //instance.updateMintV2MintsMintIdPut_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
