/**
 * Versify API
 * Versify API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Settings used to configure external integrations.
*/
export class App {
    /**
    * An application-specific list of permissions associated with the app
    */
    'accessScope'?: string;
    /**
    * The access token of the app
    */
    'accessToken'?: string;
    /**
    * The ID of the app
    */
    'id'?: string;
    /**
    * The name of the app
    */
    'name'?: string;
    /**
    * The refresh token of the app
    */
    'refreshToken'?: string;
    /**
    * The URL of the app
    */
    'url'?: string;
    /**
    * The webhook URL of the app
    */
    'webhookUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessScope",
            "baseName": "access_scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return App.attributeTypeMap;
    }

    public constructor() {
    }
}

