/**
 * Versify API
 * Versify API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Query } from '../models/Query';
import { URI } from '../models/URI';
import { WalletPosition } from '../models/WalletPosition';
import { HttpFile } from '../http/http';

/**
* The brand settings for the account
*/
export class BrandSettings {
    /**
    * The action color of the brand
    */
    'actionColor'?: string;
    /**
    * The background color of the brand
    */
    'backgroundColor'?: string;
    /**
    * The URL of the brand's logo
    */
    'logo'?: URI;
    /**
    * The primary color of the brand
    */
    'primaryColor'?: string;
    /**
    * The secondary color of the brand
    */
    'secondaryColor'?: string;
    /**
    * The tertiary color of the brand
    */
    'tertiaryColor'?: string;
    /**
    * The wallet action color of the brand
    */
    'walletActionColor'?: string;
    /**
    * The wallet background color of the brand
    */
    'walletBackgroundColor'?: string;
    /**
    * The wallet display filters of the brand
    */
    'walletDisplayFilters'?: Array<Query>;
    /**
    * The wallet position of the brand
    */
    'walletPosition'?: WalletPosition;
    /**
    * The wallet welcome message of the brand
    */
    'walletWelcomeMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "actionColor",
            "baseName": "action_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "backgroundColor",
            "baseName": "background_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "URI",
            "format": "uri"
        },
        {
            "name": "primaryColor",
            "baseName": "primary_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "secondaryColor",
            "baseName": "secondary_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "tertiaryColor",
            "baseName": "tertiary_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletActionColor",
            "baseName": "wallet_action_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletBackgroundColor",
            "baseName": "wallet_background_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletDisplayFilters",
            "baseName": "wallet_display_filters",
            "type": "Array<Query>",
            "format": ""
        },
        {
            "name": "walletPosition",
            "baseName": "wallet_position",
            "type": "WalletPosition",
            "format": ""
        },
        {
            "name": "walletWelcomeMessage",
            "baseName": "wallet_welcome_message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BrandSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

