/**
 * Versify API
 * Versify API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TeamMemberRole } from '../models/TeamMemberRole';
import { HttpFile } from '../http/http';

/**
* A team member.
*/
export class TeamMember {
    /**
    * The email of the team member
    */
    'email': string;
    /**
    * The role of the team member
    */
    'role'?: TeamMemberRole;
    /**
    * The user ID of the team member
    */
    'user'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "TeamMemberRole",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TeamMember.attributeTypeMap;
    }

    public constructor() {
    }
}

